import { v4 as uuidv4 } from "uuid";

function chillHop() {
  return [
    {
      name: "Bliss",
      artist: "Misha, Jussi Halme",
      cover: "https://cutt.ly/YmdxqNH",
      id: uuidv4(),
      active: true,
      color: ["#E97274", "#AA9AAD"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9248",
    },
    {
      name: "Lullaby",
      artist: "Misha, Jussi Halme",
      cover: "https://cutt.ly/YmdxqNH",
      id: uuidv4(),
      active: false,
      color: ["#E97274", "#AA9AAD"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=15033",
    },
    {
      name: "travelbag",
      artist: "mommy, Sleepy Fish",
      cover: "https://cutt.ly/smdcbZU",
      id: uuidv4(),
      active: false,
      color: ["#5F94D6", "#E8D8D1"],
      audio: "https://cutt.ly/YmdcFLE",
    },
    {
      name: "Simplexity",
      artist: "Evil Needle",
      cover: "https://cutt.ly/SmdcXS7",
      id: uuidv4(),
      active: false,
      color: ["#ED7052", "#E6B04E"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=14958",
    },
    {
      name: "On The Moon",
      artist: "SwuM",
      cover: "https://cutt.ly/jmdc7E1",
      id: uuidv4(),
      active: false,
      color: ["#243233", "#4F3E25"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=15237",
    },
    {
      name: "Lost Soul",
      artist: "C Y G N",
      cover: "https://cutt.ly/1mhQYqi",
      id: uuidv4(),
      active: false,
      color: ["#4F2D52", "#7B94BA"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=14989",
    },
    {
      name: "Splendour",
      artist: "Aarigod",
      cover: "https://cutt.ly/EmhQJK0",
      id: uuidv4(),
      active: false,
      color: ["#182210", "#8AB153"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=13013",
    },
    {
      name: "Beyond Clouds",
      artist: "Saib",
      cover: "https://cutt.ly/omhEslw",
      id: uuidv4(),
      active: false,
      color: ["#FBBF7B", "#1C1816"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=9297",
    },
    {
      name: "Murmuration",
      artist: "Blue Wednesday, Shopan",
      cover: "https://cutt.ly/GmhEvoG",
      id: uuidv4(),
      active: false,
      color: ["#3F426B", "#653F62"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=7814",
    },
    {
      name: "Small Town Palm Trees",
      artist: "Mama Aiuto",
      cover: "https://cutt.ly/SmhERE5",
      id: uuidv4(),
      active: false,
      color: ["#15272B", "#541F1B"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=12124",
    },
    {
      name: "Melancholy",
      artist: "Makzo",
      cover: "https://cutt.ly/HmhEH7q",
      id: uuidv4(),
      active: false,
      color: ["#3F5896", "#F49971"],
      audio: "https://mp3.chillhop.com/serve.php/?mp3=11778",
    },
  ];
}

export default chillHop;
